// react/components/Product.jsx
import React from 'react';
import {Link, Redirect} from 'react-router-dom';

class Product extends React.Component {
    constructor() {
        super();
        this.state = {
            redirect: false,
            product: {}
        }
    }

    render() {
        let redirect = '';

        if (this.state.redirect) {
            redirect = <Redirect to="/store"/>;
        }

        return (
            <div>
                {redirect}
                <h2>{this.state.product.description}</h2>
                <hr/>
                <div className="row">
                    <div className="col-md-6">
                        <img src={'./assets/img/' + this.state.product.image} className="img-thumbnail" alt={this.state.product.description}/>
                    </div>
                    <div className="col-md-6">
                        <h4><b>Precio:</b> {this.state.product.price}</h4>
                        <h4><b>Unidades Disponibles:</b> {this.state.product.stock - this.state.product.amountInCart}</h4>
                    </div>
                </div>        
                <Link to="/store" className="btn btn-secondary mt-3">Atras</Link>
            </div>
        )
    }

    componentDidMount() {
        if (this.props.products.length === 0) {
            this.setState({redirect: true});
        } else {
            const {description} = this.props.match.params;
            const result = this.props.products.filter((product) => {
                return product.description == description;
            })
    
            if (result.length > 0) {
                this.setState({
                    product: result[0]
                });
            } else {
                this.setState({redirect: true});
            }
        }
    }
}

export default Product;

// angular/src/app/product/product.component.ts
import { Component, OnInit } from '@angular/core';
import {ActivatedRoute, Router} from '@angular/router';
import {ServerService} from '../services/server.service';

@Component({
  selector: 'app-product',
  templateUrl: './product.component.html'
})
export class ProductComponent implements OnInit {

  product: any = {};

  constructor(private route: ActivatedRoute,
              private router: Router,
              private server: ServerService) {
  }

  ngOnInit() {
    this.route.params.subscribe((params: any) => {
      if (params['description'] && this.server.products.length !== 0) {


        const products: Array<any> = this.server.products.filter((product) => {
          return product.description == params['description'];
        });

        if (products.length > 0) {
          this.product = products[0];
        } else {
          this.router.navigate(['store']);
        }
      } else {
        this.router.navigate(['store']);
      }
    })
  }

  prouductInCart() {
    return this.server.amountInCart(this.product.id);
  }

}

<h2>{{ product.description }}</h2>
<hr>
<div class="row">
  <div class="col-md-6">
    <img [src]="'./assets/img/' + product.image" class="img-thumbnail" [alt]="product.description">
  </div>
  <div class="col-md-6">
    <h4><b>Precio:</b> {{ product.price }}</h4>
    <h4><b>Unidades Disponibles:</b> {{ product.stock - prouductInCart() }}</h4>
  </div>
</div>

<a routerLink="/store" class="btn btn-secondary mt-3">Atras</a>
