// react/components/Login.jsx
import React from 'react';
import {Redirect} from 'react-router-dom';
import * as request from 'superagent';
import {baseUrl} from '../configs/constants';

class Login extends React.Component {
    constructor() {
        super();
        this.state = {
            processing: false,
            redirect: false, 
            error: '',
            email: '',
            password: ''
        };
    }

    handleInputChanges(event) {
        const target = event.target;
        const name = target.name;

        this.setState({
            [name]: target.value
        });
    }

    handleSubmit(event) {
        event.preventDefault();

        this.setState({processing: true});
        request.get(`${baseUrl}/users.json`)
            .end((err,res) => {
                if (err || !res.ok) {
                    this.setState({error: 'Error en la conexion al servidor.'})
                } else {
                    const result = res.body.filter((user) => {
                        return  user && 
                                user.email == this.state.email && 
                                user.password == this.state.password;
                    });

                    if (result.length > 0) {
                        localStorage.setItem('user', JSON.stringify(result[0]));
                        this.setState({redirect: true});
                    } else {
                        this.setState({error: 'Error en el inicio de sesión'});
                    }
                }
            })
    }

    invalidForm() {
        return !this.state.password || !this.state.email
    }

    render() {
        let error = '';
        let btnText = 'Ingresar';
        let redirect = '';

        if (this.state.error) {
            error = <div className="alert alert-danger mt-3">{this.state.error}</div>;
        }

        if (this.state.processing) {
            btnText = 'Verificando';
        }

        if (this.state.redirect === true) {
            redirect = <Redirect to='/store'/>;
        }

        return (
            <div className="login-page">
                {redirect}
                <div className="login-form">
                    <form onSubmit={this.handleSubmit.bind(this)}>
                        <div className="form-group">
                            <label htmlFor="email">Correo electr&oacute;nico:</label>
                            <input type="email" 
                                name="email"
                                value={this.state.email} 
                                onChange={this.handleInputChanges.bind(this)}
                                className="form-control" 
                                id="email" 
                                required/>
                        </div>
                        <div className="form-group">
                            <label htmlFor="password">Contrase&ntilde;a:</label>
                            <input type="password" 
                                name="password" 
                                value={this.state.password}
                                onChange={this.handleInputChanges.bind(this)}
                                className="form-control" 
                                id="password" 
                                required/>
                        </div>
                        <div className="text-center">
                            <input type="submit"
                                disabled={this.processing}
                                value={btnText}
                                className="btn btn-success"/>
                        </div>
                    </form>
                    {error}
                </div>
            </div>
        )
    }
}

export default Login;

// angular/src/app/login/login.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import {ServerService} from '../services/server.service';
import {FormGroup, FormBuilder, Validators } from "@angular/forms";

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {

  processing: boolean = false;
  error: string = '';
  form: FormGroup;
  model: any = {};

  constructor(private server: ServerService,
              private router: Router,
              private fb: FormBuilder) {
    this.form = this.fb.group({
      'email': [
        null,
        Validators.compose([
          Validators.required,
          Validators.email
        ])
      ],
      'password': [null, Validators.required]
    });
  }

  public onSubmit(value: any) {
    if (this.processing) return;

    this.processing = true;
    this.error = '';
    this.server.users().subscribe(
      (users: Array<any>) => {
        this.processing = false;
        const result: any = users.filter((user) => {
          return user && user.email == value.email && user.password == value.password;
        });
        if (result.length > 0) {
          localStorage.setItem('user', JSON.stringify(result[0]));
          this.router.navigate(['store']);
        } else {
          this.error = 'Error en el inicio de sesión';
        }
      },
      () => {
        this.processing = false;
        this.error = 'Error en la conexion al servidor.';
      }
    )
  }

}

<div class="login-page">
    <div class="login-form">
      <form [formGroup]="form" (ngSubmit)="onSubmit(form.value)">
        <div class="form-group">
          <label for="email">Correo electr&oacute;nico:</label>
          <input type="email"
                 formControlName="email"
                 [ngClass]="{'is-invalid': !form.controls['email'].valid && form.controls['email'].touched } "
                 class="form-control"
                 id="email" >
          <span class="invalid-feedback"
                *ngIf="form.controls['email'].hasError('required') && form.controls['email'].touched">
            El Correo es requerido
          </span>
          <span class="invalid-feedback"
                *ngIf="form.controls['email'].hasError('email')">
            Tiene que ser un correo valido.
          </span>
        </div>
        <div class="form-group">
          <label for="password">Contrase&ntilde;a:</label>
          <input type="password"
                 formControlName="password"
                 [ngClass]="{'is-invalid': !form.controls['password'].valid && form.controls['password'].touched } "
                 class="form-control"
                 id="password" >
          <span class="invalid-feedback"
                *ngIf="form.controls['password'].hasError('required') && form.controls['password'].touched">
            La Contrase&ntilde;a es requerida
          </span>
        </div>
        <div class="text-center">
          <input type="submit"
                 [disabled]="form.invalid || processing"
                 class="btn btn-success"
                 [value]="(processing) ? 'Verificando' : 'Ingresar' ">
        </div>
      </form>
      <div class="alert alert-danger mt-3" *ngIf="error">
        <p>{{ error }}</p>
      </div>
    </div>
</div>
