// react/components/Store.jsx
import React from 'react';
import update from 'immutability-helper';
import * as request from 'superagent';
import {baseUrl} from '../configs/constants';
// Components
import Item from './Item.jsx';


class Store extends React.Component {

    constructor() {
        super();
        this.state = {
            error: '',
            search: '',
            products: [],
            productsFilter: []
        };
    }

    updateProducts(products) {
        this.setState({
            products: [...proudcts]
        });
        this.props.productChanges(products)
    }

    onSearch(event) {
        let search = event.target.value;
        let products = [];

        if (search) {
            products = this.state.products.filter((item) => {
                return item.description && item.description.toString().toLowerCase().includes(search.toLowerCase());
            });
        } else {
            products = [...this.state.products];
        }
        this.setState({
            productsFilter: products,
            search: search
        });

    }

    addProduct(product, index) {
        this.props.addProductToCart(product);
        let item = Object.assign({}, product);

        item.amountInCart += product.amount;
        item.amount = 1; 
        this.handleAmountChanges(item, index)
    }

    handleAmountChanges(product, index) {
        const updatedProducts = update(this.state.products, {$splice: [[index, 1, product]]});
        index = this.state.productsFilter.findIndex((item) => item.id === product.id);
        const updatedProductFilter = update(this.state.productsFilter, {$splice: [[index, 1, product]]})
        this.setState({
            products: updatedProducts,
            productsFilter: updatedProductFilter
        });
        this.props.productChanges(updatedProducts);
    }

    getProducts() {
        return this.state.productsFilter.map((product, index) => {
            return <Item product={product} 
                    handleAmountChanges={this.handleAmountChanges.bind(this)}
                    addProduct={this.addProduct.bind(this)} index={index} key={index}/> ;
        });
    }

    render() {
        return (
            <div>
                <div className="row">
                    <div className="col-md-8">
                        <h3>Cat&aacute;logo de productos</h3>
                    </div>
                    <div className="col-md-4">
                        <h5>¿Qu&eacute; estas buscando?</h5>
                        <input type="search" 
                            className="form-control" 
                            placeholder="Buscar producto" 
                            value={this.state.search} 
                            onChange={this.onSearch.bind(this)}/>
                    </div>
                </div>
                <hr className="mt-5 mb-2"/>
                <div className="row catalog">
                    {this.getProducts()}
                </div>
            </div>
        )
    }

    componentWillMount() {
        request.get(`${baseUrl}/products.json`).end((err, res) => {
            if (err || !res.ok) {
                this.setState({error: 'Error en la conexion al servidor.'})
            } else {
                const products = res.body.map((item) => {
                    item.amount = 1;
                    item.amountInCart = this.props.cartProducts
                        .filter(i => i.id == item.id)
                        .map(i => i.amount)
                        .reduce((current, next) => current + next, 0);

                    return item;
                });
                this.setState({
                    products: [...products],
                    productsFilter: [...products]
                });
                this.props.productChanges(products);
            }
        });
    }
}

export default Store;

// angular/src/app/store/store.component.ts
import { Component } from '@angular/core';
import {ServerService} from '../services/server.service';

@Component({
  selector: 'app-store',
  templateUrl: './store.component.html',
  styleUrls: ['./store.component.css']
})
export class StoreComponent {

  loadingProducts: boolean = false;
  error: string = '';
  search: string = '';
  productFilter: Array<any> = [];
  products: Array<any> = [];

  constructor(private server: ServerService) {
    this.loadingProducts = true;
    this.server.getProducts().subscribe(
      (products: Array<any>) => {
        this.products = products.filter((item) => !!item).map((item) => {
          item.amount = 1;
          return item;
        });
        this.server.products = [...this.products];
        this.productFilter = [...this.products];
      },
      () => {
        this.error = 'Error en la conexion al servidor.';
      }
    )
  }

  onSearch() {
    if (this.search) {
      this.productFilter = this.products.filter((item) => {
        return item.description && item.description.toString().toLowerCase().includes(this.search.toLowerCase());
      });
    } else {
      this.productFilter = [...this.products];
    }
  }

  addProduct(product) {
    if (product.amount <= 0) {
      alert('verifica que la cantidad sea un numero positivo.');
      return;
    }

    if (product.amount > (product.stock - this.amountInCart(product.id))) {
      alert('verifica que la cantidad menor o igual a las existencias.');
      return;
    }

    this.server.saveProduct(
      {
        product_id: product.id,
        image: product.image,
        description: product.description,
        amount: product.amount,
        price: product.price
      }
    );
  }

  amountInCart(id: number | string): number {
    return this.server.amountInCart(id);
  }

}

<div class="row">
  <div class="col-md-8">
    <h3>Cat&aacute;logo de productos</h3>
  </div>
  <div class="col-md-4">
    <h5>¿Qu&eacute; estas buscando?</h5>
    <input type="search" [(ngModel)]="search" (ngModelChange)="onSearch()" class="form-control" placeholder="Buscar producto">
    <pre>{{ search }}</pre>
  </div>
</div>
<hr class="mt-5 mb-2">

<div class="row catalog">
  <div class="alert" *ngIf="error">
    {{ error }}
  </div>
  <div class="col-lg-4 col-md-6 mt-3" *ngFor="let product of productFilter">
    <div class="card">
      <div class="card-image" [style.background-image]="'url(./assets/img/' + product.image +' )'"></div>
      <div class="card-body">
        <h4>{{ product.description }}</h4>
        <p><b>Precio:</b> ${{ product.price }}</p>
        <p><b>Unidades Disponibles:</b> {{ product.stock - amountInCart(product.id) }}</p>
        <div class="row mt-2">
          <div class="col-4">
            <a [routerLink]="'/store/product/' + product.description" class="btn btn-primary">Ver mas</a>
          </div>
          <div class="col-8 text-right align-text-top details">
            <button class="btn btn-warning" (click)="addProduct(product)">Agregar</button>
            <input type="number" [(ngModel)]="product.amount" min="0" [max]="product.stock" class="form-control">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
